version: '2'
volumes:
    node-red-data:
services:
  node-red:
    build: ./node-red
    volumes:
      - 'node-red-data:/data'
    restart: always
    # privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    ports:
      - 80:1880  # will make that the balena public URL maps to the node-red editor.


